 
//  <autogenerated>
//
//      This file was generated by T4 code generator 'StateEngineTamplate.tt'
//
//      Any changes made to this file manually will be PERSISTED.
//
//      This file will NOT be OVERWRITTEN at the next generation.
//      
//      Partial methods for new actions will have to be added manually.
//
//</autogenerated>
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using StateEngine4net.Shared;
using StateEngine4net.Shared.Exceptions;
using StateEngine4net.Shared.Interfaces;
using StateEngine4net.Tests.TestModel;

namespace StateEngine4net.Tests.StateEngines
{
    /// <summary>
    /// 	The RunStateController provides Actions that are to be executed on 
    /// 	state transitions. This allows modifications and interactions in
    /// 	and of the stated object when the state is about to change.
    /// </summary>
    public partial class StatedTestObjectStateEngine
    {
        // NOTE: use the following constructor in this partial specific dependencies are required
        //       in order to handle transitions, e. g. repositories, logger, etc.
        public StatedTestObjectStateEngine(/* add dependencies here */)
        {
        }

        // NOTE: implement the following partial methods in order to process the entities
        //       in accordance to the corresponding transitions
        private partial bool StartRun(StatedTestObject statedtestobject)
        {
            /* add logic here */
            return true;
        }
        private partial bool FinalizeRun(StatedTestObject statedtestobject)
        {
            /* add logic here */
            return true;
        }
        private partial bool StartCleanup(StatedTestObject statedtestobject)
        {
            /* add logic here */
            return true;
        }
    }
}

